-- Replace project.dataset with your values (same as BIGQUERY_REFINED_SERVE_STATS_TABLE_ID).
-- Run in BigQuery console or: bq query --use_legacy_sql=false < create_serve_stats.sql

CREATE TABLE IF NOT EXISTS `your_project.your_dataset.serve_stats` (
  sport_event_id STRING NOT NULL,
  competitor_id STRING NOT NULL,
  first_serve_attempts FLOAT64,
  first_serve_in FLOAT64,
  first_serve_percentage FLOAT64,
  second_serve_attempts FLOAT64,
  second_serve_in FLOAT64,
  second_serve_percentage FLOAT64,
  set_1_first_serve_attempts FLOAT64,
  set_1_first_serve_in FLOAT64,
  set_1_first_serve_percentage FLOAT64,
  set_1_second_serve_attempts FLOAT64,
  set_1_second_serve_in FLOAT64,
  set_1_second_serve_percentage FLOAT64,
  set_2_first_serve_attempts FLOAT64,
  set_2_first_serve_in FLOAT64,
  set_2_first_serve_percentage FLOAT64,
  set_2_second_serve_attempts FLOAT64,
  set_2_second_serve_in FLOAT64,
  set_2_second_serve_percentage FLOAT64,
  set_3_first_serve_attempts FLOAT64,
  set_3_first_serve_in FLOAT64,
  set_3_first_serve_percentage FLOAT64,
  set_3_second_serve_attempts FLOAT64,
  set_3_second_serve_in FLOAT64,
  set_3_second_serve_percentage FLOAT64,
  set_4_first_serve_attempts FLOAT64,
  set_4_first_serve_in FLOAT64,
  set_4_first_serve_percentage FLOAT64,
  set_4_second_serve_attempts FLOAT64,
  set_4_second_serve_in FLOAT64,
  set_4_second_serve_percentage FLOAT64,
  set_5_first_serve_attempts FLOAT64,
  set_5_first_serve_in FLOAT64,
  set_5_first_serve_percentage FLOAT64,
  set_5_second_serve_attempts FLOAT64,
  set_5_second_serve_in FLOAT64,
  set_5_second_serve_percentage FLOAT64
);
