-- Replace project.dataset with your values (same as BIGQUERY_REFINED_SERVE_STATS_TABLE_ID).
-- Run in BigQuery console or: bq query --use_legacy_sql=false < create_serve_stats.sql

CREATE TABLE IF NOT EXISTS `your_project.your_dataset.serve_stats` (
  sport_event_id STRING NOT NULL,
  competitor_id STRING NOT NULL,
  mode_best_of INT64,
  total_sets INT64,
  total_aces FLOAT64,
  first_set_ace_share FLOAT64,
  second_set_ace_share FLOAT64,
  first_serve_attempts FLOAT64,
  first_serve_in FLOAT64,
  first_serve_percentage FLOAT64,
  second_serve_attempts FLOAT64,
  second_serve_in FLOAT64,
  second_serve_percentage FLOAT64,
  set_1_first_serve_attempts FLOAT64,
  set_1_first_serve_in FLOAT64,
  set_1_first_serve_percentage FLOAT64,
  set_1_second_serve_attempts FLOAT64,
  set_1_second_serve_in FLOAT64,
  set_1_second_serve_percentage FLOAT64,
  set_1_ace_count FLOAT64,
  set_1_ace_share FLOAT64,
  set_2_first_serve_attempts FLOAT64,
  set_2_first_serve_in FLOAT64,
  set_2_first_serve_percentage FLOAT64,
  set_2_second_serve_attempts FLOAT64,
  set_2_second_serve_in FLOAT64,
  set_2_second_serve_percentage FLOAT64,
  set_2_ace_count FLOAT64,
  set_2_ace_share FLOAT64,
  set_3_first_serve_attempts FLOAT64,
  set_3_first_serve_in FLOAT64,
  set_3_first_serve_percentage FLOAT64,
  set_3_second_serve_attempts FLOAT64,
  set_3_second_serve_in FLOAT64,
  set_3_second_serve_percentage FLOAT64,
  set_3_ace_count FLOAT64,
  set_3_ace_share FLOAT64,
  set_4_first_serve_attempts FLOAT64,
  set_4_first_serve_in FLOAT64,
  set_4_first_serve_percentage FLOAT64,
  set_4_second_serve_attempts FLOAT64,
  set_4_second_serve_in FLOAT64,
  set_4_second_serve_percentage FLOAT64,
  set_4_ace_count FLOAT64,
  set_4_ace_share FLOAT64,
  set_5_first_serve_attempts FLOAT64,
  set_5_first_serve_in FLOAT64,
  set_5_first_serve_percentage FLOAT64,
  set_5_second_serve_attempts FLOAT64,
  set_5_second_serve_in FLOAT64,
  set_5_second_serve_percentage FLOAT64,
  set_5_ace_count FLOAT64,
  set_5_ace_share FLOAT64
);
